<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);tmp\**</DefaultItemExcludes>
    <UserSecretsId>atlas-pos-local-development</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Compile Remove="Atlas.PeripheralAgent\**\*.cs" />
    <Compile Remove="installer\**\*.cs" />
    <Compile Remove="release\**\*.cs" />
    <Content Remove="tests\**" />
    <None Remove="tests\**" />
    <Content Remove="Atlas.PeripheralAgent\**" />
    <None Remove="Atlas.PeripheralAgent\**" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="System.IO.Ports" Version="10.0.10" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
  </ItemGroup>

</Project>
