// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuntoDeVentaAtlas.Web.Data;

#nullable disable

namespace PuntoDeVentaAtlas.Web.Data.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260915180432_UniqueOpenShiftPerTerminal")]
    partial class UniqueOpenShiftPerTerminal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.AuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("longtext")
                        .HasColumnName("detail");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext")
                        .HasColumnName("entity_id");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.CashMovementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<long>("ShiftId")
                        .HasColumnType("bigint")
                        .HasColumnName("shift_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("cash_movements", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.CashShiftEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closed_at");

                    b.Property<decimal?>("CountedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("counted_amount");

                    b.Property<decimal?>("ExpectedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_amount");

                    b.Property<string>("OpenShiftKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("open_shift_key")
                        .HasComputedColumnSql("CASE WHEN status = 'open' THEN '1' ELSE NULL END", true);

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("OpeningAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("opening_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkstationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "UserId", "WorkstationId", "OpenShiftKey")
                        .IsUnique();

                    b.ToTable("cash_shifts", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.CategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.CustomerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CfdiUse")
                        .HasColumnType("longtext")
                        .HasColumnName("cfdi_use");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FiscalRegime")
                        .HasColumnType("longtext")
                        .HasColumnName("fiscal_regime");

                    b.Property<string>("FiscalZip")
                        .HasColumnType("longtext")
                        .HasColumnName("fiscal_zip");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Rfc")
                        .HasColumnType("longtext")
                        .HasColumnName("rfc");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.InventoryMovementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<long?>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("StockAfter")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("stock_after");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.InvoiceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Pdf")
                        .HasColumnType("longblob")
                        .HasColumnName("pdf");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rfc");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.Property<DateTime?>("StampedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("stamped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Uuid")
                        .HasColumnType("longtext")
                        .HasColumnName("uuid");

                    b.Property<byte[]>("Xml")
                        .HasColumnType("longblob")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PaymentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Authorization")
                        .HasColumnType("longtext")
                        .HasColumnName("authorization");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<string>("Provider")
                        .HasColumnType("longtext")
                        .HasColumnName("provider");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext")
                        .HasColumnName("reference");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PeripheralConfigurationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("connection_type");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext")
                        .HasColumnName("device_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Endpoint")
                        .HasColumnType("longtext")
                        .HasColumnName("endpoint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("key");

                    b.Property<string>("LastMessage")
                        .HasColumnType("longtext")
                        .HasColumnName("last_message");

                    b.Property<string>("LastStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_status");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_tested_at");

                    b.Property<string>("Mode")
                        .HasColumnType("longtext")
                        .HasColumnName("mode");

                    b.Property<int?>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<string>("ProtectedSecret")
                        .HasColumnType("longtext")
                        .HasColumnName("protected_secret");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("provider");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkstationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "WorkstationId", "Key")
                        .IsUnique();

                    b.ToTable("peripheral_configurations", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Barcode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("barcode");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cost");

                    b.Property<bool>("IsWeighted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_weighted");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("minimum_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sku");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("stock");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(7,4)")
                        .HasColumnName("tax_rate");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId", "Barcode")
                        .IsUnique();

                    b.HasIndex("StoreId", "Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.ProductionOrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Batches")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("batches");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("folio");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityProduced")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity_produced");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("production_orders", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PurchaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("folio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PurchaseLineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.ToTable("purchase_lines", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.RecipeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<decimal>("OutputQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("output_quantity");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.RecipeLineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_lines", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientOperationId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("client_operation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("folio");

                    b.Property<long>("ShiftId")
                        .HasColumnType("bigint")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("WorkstationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StoreId", "ClientOperationId")
                        .IsUnique();

                    b.HasIndex("StoreId", "Folio")
                        .IsUnique();

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleLineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_lines", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleReturnEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("folio");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("sale_returns", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleReturnLineEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<bool>("Restocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("restocked");

                    b.Property<long>("ReturnId")
                        .HasColumnType("bigint")
                        .HasColumnName("return_id");

                    b.Property<long>("SaleLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_line_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("sale_return_lines", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SignatureEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("BiometricData")
                        .HasColumnType("longblob")
                        .HasColumnName("biometric_data");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("captured_at");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext")
                        .HasColumnName("device_id");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("image");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.HasKey("Id");

                    b.ToTable("signatures", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.StoreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Rfc")
                        .HasColumnType("longtext")
                        .HasColumnName("rfc");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SupplierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Rfc")
                        .HasColumnType("longtext")
                        .HasColumnName("rfc");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.WorkstationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("terminal_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "TerminalId")
                        .IsUnique();

                    b.ToTable("workstations", (string)null);
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.CashMovementEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.CashShiftEntity", null)
                        .WithMany("Movements")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PaymentEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.SaleEntity", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.ProductEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PurchaseEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PurchaseLineEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.PurchaseEntity", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.RecipeEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.RecipeLineEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuntoDeVentaAtlas.Web.Data.RecipeEntity", null)
                        .WithMany("Components")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.CashShiftEntity", "Shift")
                        .WithMany("Sales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleLineEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.SaleEntity", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleReturnLineEntity", b =>
                {
                    b.HasOne("PuntoDeVentaAtlas.Web.Data.SaleReturnEntity", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.CashShiftEntity", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.PurchaseEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.RecipeEntity", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleEntity", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PuntoDeVentaAtlas.Web.Data.SaleReturnEntity", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
