using System.Globalization;
using System.Text;
using PuntoDeVentaAtlas.Web.Models;
namespace PuntoDeVentaAtlas.Web.Services;
public sealed class CustomerDashboardPdfService
{
 public byte[] Create(CustomerDashboard d){var c=new StringBuilder();c.AppendLine("0.08 0.12 0.20 rg 0 730 612 62 re f");Text(c,42,762,20,"ATLAS POS - DASHBOARD DE CLIENTES",true,"1 1 1");Text(c,42,738,9,$"Generado: {DateTime.Now:dd/MM/yyyy HH:mm}",false,"0.82 0.87 0.94");Text(c,42,690,12,"RESUMEN",true);Metric(c,42,620,120,"Clientes",d.Total.ToString());Metric(c,174,620,120,"Con RFC",d.WithRfc.ToString());Metric(c,306,620,120,"Con correo",d.WithEmail.ToString());Metric(c,438,620,120,"Listos CFDI",d.FiscalReady.ToString());Text(c,42,580,12,"CALIDAD DEL DIRECTORIO",true);var y=540;foreach(var s in d.Segments){Text(c,42,y+15,10,$"{s.Name}: {s.Count} ({s.Percentage:0.0}%)",false);c.AppendLine($"0.90 0.92 0.95 rg 42 {y-2} 500 12 re f");c.AppendLine($"0.16 0.40 0.87 rg 42 {y-2} {Math.Round(500m*s.Percentage/100m,1).ToString(CultureInfo.InvariantCulture)} 12 re f");y-=62;}Text(c,42,190,10,"Criterio fiscal: RFC, razon social, regimen, codigo postal y uso CFDI completos.",false,"0.35 0.40 0.48");Text(c,42,54,9,"Atlas POS | Reporte operativo interno",false,"0.45 0.50 0.58");return Build(c.ToString());}
 static void Metric(StringBuilder c,int x,int y,int w,string label,string value){c.AppendLine($"0.96 0.97 0.99 rg {x} {y} {w} 58 re f");Text(c,x+12,y+35,9,label,false,"0.38 0.43 0.51");Text(c,x+12,y+13,18,value,true);}
 static void Text(StringBuilder c,int x,int y,int size,string value,bool bold,string color="0.08 0.12 0.20")=>c.AppendLine($"BT /{(bold?"F2":"F1")} {size} Tf {color} rg {x} {y} Td ({Esc(Ascii(value))}) Tj ET");
 static string Ascii(string v)=>string.Concat(v.Normalize(NormalizationForm.FormD).Where(x=>CharUnicodeInfo.GetUnicodeCategory(x)!=UnicodeCategory.NonSpacingMark)).Normalize();static string Esc(string v)=>v.Replace("\\","\\\\").Replace("(","\\(").Replace(")","\\)");
 static byte[] Build(string stream){var o=new[]{"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",$"<< /Length {Encoding.ASCII.GetByteCount(stream)} >>\nstream\n{stream}endstream","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"};using var m=new MemoryStream();void W(string s){m.Write(Encoding.ASCII.GetBytes(s));}W("%PDF-1.4\n");var p=new List<long>{0};for(var i=0;i<o.Length;i++){p.Add(m.Position);W($"{i+1} 0 obj\n{o[i]}\nendobj\n");}var x=m.Position;W($"xref\n0 {o.Length+1}\n0000000000 65535 f \n");for(var i=1;i<p.Count;i++)W($"{p[i]:0000000000} 00000 n \n");W($"trailer << /Size {o.Length+1} /Root 1 0 R >>\nstartxref\n{x}\n%%EOF");return m.ToArray();}
}
