using System.Data;
using Microsoft.EntityFrameworkCore;
using PuntoDeVentaAtlas.Web.Data;
using PuntoDeVentaAtlas.Web.Models;
using PuntoDeVentaAtlas.Web.Domain;

namespace PuntoDeVentaAtlas.Web.Services;

public interface IMySqlPointOfSaleService
{
    Task<DashboardViewModel> DashboardAsync(CancellationToken ct); Task<SaleResult> CheckoutAsync(SaleRequest request,CancellationToken ct);
    Task<Product> SaveProductAsync(ProductUpsertRequest request,CancellationToken ct); Task<Customer> SaveCustomerAsync(CustomerUpsertRequest request,CancellationToken ct);
    Task<IReadOnlyList<Supplier>> SuppliersAsync(CancellationToken ct); Task<IReadOnlyList<PurchaseSummary>> PurchasesAsync(CancellationToken ct);
    Task<CashShiftSummary> CurrentShiftAsync(CancellationToken ct); Task<CashShiftSummary> CloseShiftAsync(decimal countedAmount,CancellationToken ct); Task<CashShiftSummary> OpenShiftAsync(decimal openingAmount,CancellationToken ct); Task<CashShiftSummary> AddCashMovementAsync(CashMovementRequest request,CancellationToken ct);
    Task<IReadOnlyList<AuditEntry>> AuditAsync(CancellationToken ct);
    Task<CustomerDashboard> CustomerDashboardAsync(CancellationToken ct);
    Task<PurchaseSummary> ReceivePurchaseAsync(PurchaseRequest request,CancellationToken ct); Task<ReturnableSale> ReturnableSaleAsync(string folio,CancellationToken ct); Task<ReturnResult> ReturnSaleAsync(ReturnRequest request,CancellationToken ct); Task<InventoryAdjustmentResult> AdjustInventoryAsync(InventoryAdjustmentRequest request,CancellationToken ct);
}

public sealed class EfPointOfSaleService(AtlasDbContext db,ICurrentUserContext current,ICurrentTerminalContext terminal) : IMySqlPointOfSaleService
{
    private long StoreId=>current.StoreId; private long UserId=>current.UserId;
    private string WorkstationId=>terminal.TerminalId;
    public async Task<DashboardViewModel> DashboardAsync(CancellationToken ct)
    {
        var colors=new[]{"#c96f3b","#5a8dee","#ef6262","#d49a62","#8769d4","#33a6a6","#e0ad38","#bc7a54"};
        var rows=await db.Products.AsNoTracking().Include(x=>x.Category).Where(x=>x.StoreId==StoreId&&x.Active).OrderBy(x=>x.Name).ToListAsync(ct);
        var products=rows.Select((x,i)=>new Product((int)x.Id,x.Sku,x.Barcode??"",x.Name,x.Category?.Name??"General",x.Price,x.Stock,x.Unit,x.IsWeighted,x.TaxRate,colors[i%colors.Length])).ToList();
        var customers=await db.Customers.AsNoTracking().Where(x=>x.StoreId==StoreId).OrderBy(x=>x.Id).Select(x=>new Customer((int)x.Id,x.Name,x.Rfc??"",x.Email??"",x.Phone??"")).ToListAsync(ct);
        var today=DateTime.Today;var sales=await db.Sales.AsNoTracking().Where(x=>x.StoreId==StoreId&&x.CreatedAt>=today&&x.Status=="completed").ToListAsync(ct);
        var recent=await db.Sales.AsNoTracking().Where(x=>x.StoreId==StoreId).OrderByDescending(x=>x.Id).Take(8).Select(x=>new SaleResult(x.Folio,x.CreatedAt,x.Subtotal,x.Discount,x.Tax,x.Total,x.Total,0,new List<SaleTicketLine>(),new List<PaymentRequest>(),"Administrador")).ToListAsync(ct);
        return new(products,customers,recent,sales.Sum(x=>x.Total),sales.Count,products.Count(x=>x.Stock<=10),await CustomerDashboardAsync(ct));
    }
    public async Task<CustomerDashboard> CustomerDashboardAsync(CancellationToken ct)
    {
        var rows=await db.Customers.AsNoTracking().Where(x=>x.StoreId==StoreId).Select(x=>new{x.Rfc,x.Email,x.Phone,x.LegalName,x.FiscalRegime,x.FiscalZip,x.CfdiUse}).ToListAsync(ct);
        var total=rows.Count; var rfc=rows.Count(x=>!string.IsNullOrWhiteSpace(x.Rfc)); var email=rows.Count(x=>!string.IsNullOrWhiteSpace(x.Email)); var phone=rows.Count(x=>!string.IsNullOrWhiteSpace(x.Phone));
        var fiscal=rows.Count(x=>!string.IsNullOrWhiteSpace(x.Rfc)&&!string.IsNullOrWhiteSpace(x.LegalName)&&!string.IsNullOrWhiteSpace(x.FiscalRegime)&&!string.IsNullOrWhiteSpace(x.FiscalZip)&&!string.IsNullOrWhiteSpace(x.CfdiUse));
        decimal P(int n)=>total==0?0:decimal.Round(n*100m/total,1);
        return new(total,rfc,email,phone,fiscal,[new("Listos para facturar",fiscal,P(fiscal)),new("Con RFC",rfc,P(rfc)),new("Con correo",email,P(email)),new("Con teléfono",phone,P(phone))]);
    }
    public async Task<SaleResult> CheckoutAsync(SaleRequest request,CancellationToken ct)
    {
        for(var attempt=1;attempt<=3;attempt++)
        {
            try{return await CheckoutCoreAsync(request,ct);}
            catch(Exception ex) when(IsConcurrencyFailure(ex)&&attempt<3){db.ChangeTracker.Clear();await Task.Delay(TimeSpan.FromMilliseconds(80*attempt),ct);}
            catch(Exception ex) when(IsDuplicate(ex))
            {
                db.ChangeTracker.Clear();var previous=await db.Sales.AsNoTracking().FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.ClientOperationId==request.ClientOperationId,ct);if(previous is not null)return PreviousSale(previous,request);throw;
            }
        }
        throw new InvalidOperationException("No fue posible completar la venta por concurrencia. Reintenta con la misma operación.");
    }
    private async Task<SaleResult> CheckoutCoreAsync(SaleRequest request,CancellationToken ct)
    {
        request.ClientOperationId=request.ClientOperationId.Trim();
        if(string.IsNullOrWhiteSpace(request.ClientOperationId)||request.ClientOperationId.Length>64)throw new InvalidOperationException("La operación de venta no tiene un identificador válido.");
        if(request.Lines.Count==0||request.Lines.Count>200)throw new InvalidOperationException("Agrega entre 1 y 200 productos.");
        if(request.Payments.Count==0)throw new InvalidOperationException("Selecciona una forma de pago.");
        var methods=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"cash","card","transfer"};
        if(request.Payments.Any(x=>!methods.Contains(x.Method)))throw new InvalidOperationException("La forma de pago no es válida.");
        if(request.Payments.Any(x=>x.Amount<=0))throw new InvalidOperationException("El importe de pago debe ser mayor que cero.");
        if(request.Payments.Any(x=>!x.Method.Equals("cash",StringComparison.OrdinalIgnoreCase)&&string.IsNullOrWhiteSpace(x.Reference)))throw new InvalidOperationException("Tarjeta y transferencia requieren referencia o autorización.");
        if(request.DiscountPercent>0&&current.Role is not ("Administrator" or "Manager"))throw new InvalidOperationException("El descuento requiere autorización de encargado.");
        await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);
        var previous=await db.Sales.AsNoTracking().FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.ClientOperationId==request.ClientOperationId,ct);
        if(previous is not null)return PreviousSale(previous,request);
        var groups=request.Lines.GroupBy(x=>x.ProductId).Select(g=>new{ProductId=g.Key,Quantity=g.Sum(x=>x.Quantity)}).ToList();
        if(groups.Any(x=>x.ProductId<=0||x.Quantity<=0))throw new InvalidOperationException("La cantidad de cada producto debe ser mayor que cero.");
        var ids=groups.Select(x=>(long)x.ProductId).ToList();var products=await db.Products.Where(x=>x.StoreId==StoreId&&x.Active&&ids.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct);
        if(products.Count!=ids.Count)throw new InvalidOperationException("Uno de los productos no pertenece a esta sucursal o está inactivo.");
        if(groups.Any(x=>x.Quantity>products[x.ProductId].Stock))throw new InvalidOperationException("La existencia solicitada supera el stock disponible.");
        var calculated=SaleCalculator.Calculate(groups.Select(x=>(products[x.ProductId].Price,x.Quantity,products[x.ProductId].TaxRate)),request.DiscountPercent);var subtotal=calculated.Subtotal;var tax=calculated.Tax;var discount=calculated.Discount;var total=calculated.Total;var paid=Round(request.Payments.Sum(x=>x.Amount));if(paid<total)throw new InvalidOperationException("El pago no cubre el total de la venta.");
        var customerId=request.CustomerId;
        if(customerId is not null&&!await db.Customers.AnyAsync(x=>x.Id==customerId&&x.StoreId==StoreId,ct))throw new InvalidOperationException("El cliente no pertenece a esta sucursal.");
        var shift=await db.CashShifts.FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.UserId==UserId&&x.WorkstationId==WorkstationId&&x.Status=="open",ct)??throw new InvalidOperationException("Abre tu turno en esta caja antes de cobrar.");
        var sale=new SaleEntity{StoreId=StoreId,WorkstationId=WorkstationId,ClientOperationId=request.ClientOperationId,Shift=shift,CustomerId=customerId,Folio=$"V-{DateTime.Now:yyyyMMdd-HHmmssfff}-{Guid.NewGuid():N}"[..30],Subtotal=subtotal,Discount=discount,Tax=tax,Total=total,Status="completed",CreatedAt=DateTime.Now};
        var ticket=new List<SaleTicketLine>();foreach(var item in groups){var p=products[item.ProductId];var baseAmount=Round(p.Price*item.Quantity);var lineTax=Round(baseAmount*p.TaxRate);var lineTotal=baseAmount+lineTax;ticket.Add(new(p.Name,item.Quantity,p.Unit,p.Price,lineTotal));p.Stock-=item.Quantity;sale.Lines.Add(new(){ProductId=p.Id,Description=p.Name,Quantity=item.Quantity,UnitPrice=p.Price,Tax=lineTax,Total=lineTotal});db.InventoryMovements.Add(new(){ProductId=p.Id,UserId=UserId,SaleId=null,Kind="sale",Quantity=-item.Quantity,StockAfter=p.Stock,Note=sale.Folio,CreatedAt=DateTime.Now});}
        decimal remaining=total;foreach(var p in request.Payments){var applied=Math.Min(p.Amount,remaining);if(applied<=0)continue;sale.Payments.Add(new(){Method=p.Method.ToLowerInvariant(),Amount=applied,Reference=p.Reference?.Trim(),Status="approved",CreatedAt=DateTime.Now});remaining-=applied;}db.Sales.Add(sale);db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="sale.completed",Entity="sale",EntityId=sale.Folio,Detail=$"{{\"total\":{total}}}"});await db.SaveChangesAsync(ct);
        foreach(var movement in db.ChangeTracker.Entries<InventoryMovementEntity>().Where(x=>x.Entity.Note==sale.Folio))movement.Entity.SaleId=sale.Id;await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(sale.Folio,sale.CreatedAt,subtotal,discount,tax,total,paid,paid-total,ticket,request.Payments,current.Name);
    }
    private SaleResult PreviousSale(SaleEntity previous,SaleRequest request)=>new(previous.Folio,previous.CreatedAt,previous.Subtotal,previous.Discount,previous.Tax,previous.Total,previous.Total,0,[],request.Payments,current.Name);
    private static bool IsDuplicate(Exception ex)=>FindMySql(ex)?.Number==1062;
    private static bool IsConcurrencyFailure(Exception ex)=>FindMySql(ex)?.Number is 1205 or 1213;
    private static MySqlConnector.MySqlException? FindMySql(Exception? ex){while(ex is not null){if(ex is MySqlConnector.MySqlException mysql)return mysql;ex=ex.InnerException;}return null;}
    public async Task<Product> SaveProductAsync(ProductUpsertRequest x,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var category=await db.Categories.FirstOrDefaultAsync(c=>c.StoreId==StoreId&&c.Name==x.Category.Trim(),ct);if(category is null){category=new(){StoreId=StoreId,Name=x.Category.Trim()};db.Categories.Add(category);}ProductEntity entity;if(x.Id is null){entity=new(){StoreId=StoreId};db.Products.Add(entity);}else entity=await db.Products.FirstOrDefaultAsync(p=>p.Id==x.Id&&p.StoreId==StoreId,ct)??throw new InvalidOperationException("Producto no encontrado.");var previousStock=entity.Stock;entity.Category=category;entity.Sku=x.Sku.Trim();entity.Barcode=string.IsNullOrWhiteSpace(x.Barcode)?null:x.Barcode.Trim();entity.Name=x.Name.Trim();entity.Price=x.Price;entity.Cost=x.Cost;entity.Stock=x.Stock;entity.TaxRate=x.TaxRate;entity.Unit=x.Unit.Trim();entity.IsWeighted=x.IsWeighted;db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="product.saved",Entity="product",EntityId=entity.Sku});await db.SaveChangesAsync(ct);if(previousStock!=entity.Stock){db.InventoryMovements.Add(new(){ProductId=entity.Id,UserId=UserId,Kind=x.Id is null?"initial":"adjustment.count",Quantity=entity.Stock-previousStock,StockAfter=entity.Stock,Note=x.Id is null?"Alta de producto":"Cambio de existencia desde catálogo",CreatedAt=DateTime.Now});await db.SaveChangesAsync(ct);}await tx.CommitAsync(ct);return new((int)entity.Id,entity.Sku,entity.Barcode??"",entity.Name,category.Name,entity.Price,entity.Stock,entity.Unit,entity.IsWeighted,entity.TaxRate,"#2865df");}
    public async Task<Customer> SaveCustomerAsync(CustomerUpsertRequest x,CancellationToken ct){CustomerEntity entity;if(x.Id is null){entity=new(){StoreId=StoreId};db.Customers.Add(entity);}else entity=await db.Customers.FirstOrDefaultAsync(c=>c.Id==x.Id&&c.StoreId==StoreId,ct)??throw new InvalidOperationException("Cliente no encontrado.");entity.Name=x.Name.Trim();entity.Rfc=CleanUpper(x.Rfc);entity.Email=x.Email?.Trim().ToLowerInvariant();entity.Phone=x.Phone?.Trim();entity.LegalName=x.LegalName?.Trim();entity.FiscalRegime=x.FiscalRegime?.Trim();entity.FiscalZip=x.FiscalZip?.Trim();entity.CfdiUse=CleanUpper(x.CfdiUse);db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="customer.saved",Entity="customer",EntityId=entity.Rfc});await db.SaveChangesAsync(ct);return new((int)entity.Id,entity.Name,entity.Rfc??"",entity.Email??"",entity.Phone??"");}
    public async Task<IReadOnlyList<Supplier>> SuppliersAsync(CancellationToken ct)=>await db.Suppliers.AsNoTracking().Where(x=>x.StoreId==StoreId).OrderBy(x=>x.Name).Select(x=>new Supplier((int)x.Id,x.Name,x.Rfc??"",x.Email??"",x.Phone??"",x.Active)).ToListAsync(ct);
    public async Task<IReadOnlyList<PurchaseSummary>> PurchasesAsync(CancellationToken ct)=>await db.Purchases.AsNoTracking().Where(x=>x.StoreId==StoreId).OrderByDescending(x=>x.Id).Take(100).Select(x=>new PurchaseSummary(x.Id,x.Folio,x.Supplier.Name,x.Total,x.CreatedAt,x.Status)).ToListAsync(ct);
    public async Task<IReadOnlyList<AuditEntry>> AuditAsync(CancellationToken ct)=>await (from a in db.AuditLog.AsNoTracking() join u in db.Users.AsNoTracking() on a.UserId equals u.Id into users from u in users.DefaultIfEmpty() where a.StoreId==StoreId orderby a.Id descending select new AuditEntry(a.Id,u==null?"Sistema":u.Name,a.Action,a.Entity,a.EntityId,a.CreatedAt)).Take(100).ToListAsync(ct);
    public async Task<PurchaseSummary> ReceivePurchaseAsync(PurchaseRequest request,CancellationToken ct)
    {
        if(request.Lines.Count==0)throw new InvalidOperationException("La compra no tiene productos.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);
        var supplier=await db.Suppliers.FirstOrDefaultAsync(x=>x.Id==request.SupplierId&&x.StoreId==StoreId&&x.Active,ct)??throw new InvalidOperationException("Proveedor no encontrado.");var ids=request.Lines.Select(x=>(long)x.ProductId).Distinct().ToList();var products=await db.Products.Where(x=>x.StoreId==StoreId&&ids.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct);decimal total=0;
        var purchase=new PurchaseEntity{StoreId=StoreId,Supplier=supplier,Folio=request.Reference?.Trim() is {Length:>0} reference?reference:$"C-{DateTime.Now:yyyyMMdd-HHmmssfff}",Status="received",CreatedAt=DateTime.Now};
        foreach(var line in request.Lines){if(!products.TryGetValue(line.ProductId,out var product))throw new InvalidOperationException("Producto de compra no encontrado.");var lineTotal=Round(line.Quantity*line.UnitCost);total+=lineTotal;product.Stock+=line.Quantity;product.Cost=line.UnitCost;purchase.Lines.Add(new(){ProductId=product.Id,Quantity=line.Quantity,UnitCost=line.UnitCost,Total=lineTotal});db.InventoryMovements.Add(new(){ProductId=product.Id,UserId=UserId,Kind="purchase",Quantity=line.Quantity,StockAfter=product.Stock,Note=purchase.Folio,CreatedAt=DateTime.Now});}
        purchase.Total=Round(total);db.Purchases.Add(purchase);db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="purchase.received",Entity="purchase",EntityId=purchase.Folio,Detail=$"{{\"total\":{purchase.Total}}}"});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(purchase.Id,purchase.Folio,supplier.Name,purchase.Total,purchase.CreatedAt,purchase.Status);
    }
    public async Task<ReturnableSale> ReturnableSaleAsync(string folio,CancellationToken ct)
    {
        var sale=await db.Sales.AsNoTracking().Include(x=>x.Lines).FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.Folio==folio,ct)??throw new InvalidOperationException("Venta no encontrada.");
        var returned=await db.SaleReturnLines.AsNoTracking().Where(x=>sale.Lines.Select(l=>l.Id).Contains(x.SaleLineId)).GroupBy(x=>x.SaleLineId).Select(x=>new{x.Key,Quantity=x.Sum(y=>y.Quantity)}).ToDictionaryAsync(x=>x.Key,x=>x.Quantity,ct);
        var ratio=sale.Lines.Sum(x=>x.Total)==0?0:sale.Total/sale.Lines.Sum(x=>x.Total);var lines=sale.Lines.Select(x=>{var qty=returned.GetValueOrDefault(x.Id);return new ReturnableSaleLine(x.Id,x.Description,x.Quantity,qty,Math.Max(0,x.Quantity-qty),"pza",Round(x.Total/x.Quantity*ratio));}).ToList();return new(sale.Folio,sale.Status,sale.Total,lines);
    }
    public async Task<ReturnResult> ReturnSaleAsync(ReturnRequest request,CancellationToken ct)
    {
        if(request.Lines.Count==0)throw new InvalidOperationException("Selecciona al menos un producto para devolver.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);
        var sale=await db.Sales.Include(x=>x.Lines).Include(x=>x.Payments).FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.Folio==request.SaleFolio,ct)??throw new InvalidOperationException("Venta no encontrada.");if(sale.Status is not ("completed" or "partially_returned"))throw new InvalidOperationException("La venta ya no admite devoluciones.");
        var duplicate=request.Lines.GroupBy(x=>x.SaleLineId).Any(x=>x.Count()>1);if(duplicate)throw new InvalidOperationException("Hay renglones duplicados en la devolución.");var saleLineIds=sale.Lines.Select(x=>x.Id).ToList();var prior=await db.SaleReturnLines.Where(x=>saleLineIds.Contains(x.SaleLineId)).GroupBy(x=>x.SaleLineId).Select(x=>new{x.Key,Quantity=x.Sum(y=>y.Quantity)}).ToDictionaryAsync(x=>x.Key,x=>x.Quantity,ct);var products=await db.Products.Where(x=>x.StoreId==StoreId&&sale.Lines.Select(l=>l.ProductId).Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct);var folio=$"D-{DateTime.Now:yyyyMMdd-HHmmssfff}";var sumLines=sale.Lines.Sum(x=>x.Total);var ratio=sumLines==0?0:sale.Total/sumLines;var entity=new SaleReturnEntity{StoreId=StoreId,SaleId=sale.Id,Folio=folio,Reason=request.Reason.Trim(),Status="refund_pending",CreatedAt=DateTime.Now};decimal refund=0;
        foreach(var item in request.Lines){var line=sale.Lines.FirstOrDefault(x=>x.Id==item.SaleLineId)??throw new InvalidOperationException("Uno de los productos no pertenece a la venta.");var available=line.Quantity-prior.GetValueOrDefault(line.Id);if(item.Quantity<=0||item.Quantity>available)throw new InvalidOperationException($"Cantidad inválida para {line.Description}. Disponible para devolver: {available}.");var amount=Round(line.Total/line.Quantity*item.Quantity*ratio);refund+=amount;entity.Lines.Add(new(){SaleLineId=line.Id,ProductId=line.ProductId,Quantity=item.Quantity,Total=amount,Restocked=item.Restock});if(item.Restock){var product=products[line.ProductId];product.Stock+=item.Quantity;db.InventoryMovements.Add(new(){ProductId=product.Id,UserId=UserId,SaleId=sale.Id,Kind="return",Quantity=item.Quantity,StockAfter=product.Stock,Note=folio,CreatedAt=DateTime.Now});}}
        entity.Total=Round(refund);db.SaleReturns.Add(entity);await db.SaveChangesAsync(ct);var totalReturned=await db.SaleReturnLines.Where(x=>saleLineIds.Contains(x.SaleLineId)).SumAsync(x=>x.Quantity,ct);sale.Status=totalReturned>=sale.Lines.Sum(x=>x.Quantity)?"returned":"partially_returned";db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="sale.returned",Entity="sale",EntityId=sale.Folio,Detail=$"{{\"returnFolio\":\"{folio}\",\"total\":{entity.Total}}}"});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(folio,entity.Total,sale.Status);
    }
    public async Task<InventoryAdjustmentResult> AdjustInventoryAsync(InventoryAdjustmentRequest request,CancellationToken ct)
    {
        await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var product=await db.Products.FirstOrDefaultAsync(x=>x.Id==request.ProductId&&x.StoreId==StoreId&&x.Active,ct)??throw new InvalidOperationException("Producto no encontrado.");var before=product.Stock;var difference=request.Kind switch{"in"=>request.Quantity,"out"=>-request.Quantity,"waste"=>-request.Quantity,"count"=>request.Quantity-before,_=>throw new InvalidOperationException("Tipo de ajuste no válido.")};if(before+difference<0)throw new InvalidOperationException("El ajuste dejaría existencia negativa.");product.Stock+=difference;db.InventoryMovements.Add(new(){ProductId=product.Id,UserId=UserId,Kind=request.Kind=="waste"?"waste":$"adjustment.{request.Kind}",Quantity=difference,StockAfter=product.Stock,Note=request.Reason.Trim(),CreatedAt=DateTime.Now});db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="inventory.adjusted",Entity="product",EntityId=product.Sku,Detail=$"{{\"kind\":\"{request.Kind}\",\"difference\":{difference}}}"});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new((int)product.Id,before,product.Stock,difference,request.Kind);
    }
    public async Task<CashShiftSummary> CurrentShiftAsync(CancellationToken ct){var shift=await db.CashShifts.AsNoTracking().Include(x=>x.Sales).ThenInclude(x=>x.Payments).Include(x=>x.Movements).OrderByDescending(x=>x.Id).FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.UserId==UserId&&x.WorkstationId==WorkstationId&&x.Status=="open",ct)??throw new InvalidOperationException("No tienes un turno abierto en esta caja.");return MapShift(shift);}
    public async Task<CashShiftSummary> OpenShiftAsync(decimal openingAmount,CancellationToken ct){if(openingAmount<0)throw new InvalidOperationException("El fondo inicial no puede ser negativo.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);if(await db.CashShifts.AnyAsync(x=>x.StoreId==StoreId&&x.UserId==UserId&&x.WorkstationId==WorkstationId&&x.Status=="open",ct))throw new InvalidOperationException("Ya tienes un turno abierto en esta caja.");var shift=new CashShiftEntity{StoreId=StoreId,UserId=UserId,WorkstationId=WorkstationId,OpenedAt=DateTime.Now,OpeningAmount=Round(openingAmount),Status="open"};db.CashShifts.Add(shift);db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="shift.opened",Entity="cash_shift",Detail=$"{{\"openingAmount\":{shift.OpeningAmount},\"terminal\":\"{WorkstationId}\"}}"});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return MapShift(shift);}
    public async Task<CashShiftSummary> AddCashMovementAsync(CashMovementRequest request,CancellationToken ct){if(request.Kind is not ("deposit" or "withdrawal")||request.Amount<=0||string.IsNullOrWhiteSpace(request.Reason))throw new InvalidOperationException("El movimiento requiere tipo, monto positivo y motivo.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var shift=await db.CashShifts.Include(x=>x.Sales).ThenInclude(x=>x.Payments).Include(x=>x.Movements).FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.UserId==UserId&&x.WorkstationId==WorkstationId&&x.Status=="open",ct)??throw new InvalidOperationException("No tienes un turno abierto en esta caja.");if(request.Kind=="withdrawal"&&request.Amount>MapShift(shift).ExpectedAmount)throw new InvalidOperationException("El retiro supera el efectivo esperado.");shift.Movements.Add(new(){UserId=UserId,Kind=request.Kind,Amount=Round(request.Amount),Reason=request.Reason.Trim(),CreatedAt=DateTime.Now});db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action=$"cash.{request.Kind}",Entity="cash_shift",EntityId=shift.Id.ToString(),Detail=$"{{\"amount\":{Round(request.Amount)}}}"});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return MapShift(shift);}
    public async Task<CashShiftSummary> CloseShiftAsync(decimal counted,CancellationToken ct){if(counted<0)throw new InvalidOperationException("El efectivo contado no puede ser negativo.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var shift=await db.CashShifts.Include(x=>x.Sales).ThenInclude(x=>x.Payments).Include(x=>x.Movements).OrderByDescending(x=>x.Id).FirstOrDefaultAsync(x=>x.StoreId==StoreId&&x.UserId==UserId&&x.WorkstationId==WorkstationId&&x.Status=="open",ct)??throw new InvalidOperationException("No tienes un turno abierto en esta caja.");var summary=MapShift(shift);shift.ClosedAt=DateTime.Now;shift.ExpectedAmount=summary.ExpectedAmount;shift.CountedAmount=Round(counted);shift.Status="closed";db.AuditLog.Add(new(){StoreId=StoreId,UserId=UserId,Action="shift.closed",Entity="cash_shift",EntityId=shift.Id.ToString(),Detail=$"{{\"difference\":{Round(counted-summary.ExpectedAmount)}}}"});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return summary with{ClosedAt=shift.ClosedAt,Status="closed",CountedAmount=shift.CountedAmount};}
    private static CashShiftSummary MapShift(CashShiftEntity x){var cash=x.Sales.Where(s=>s.Status=="completed").SelectMany(s=>s.Payments).Where(p=>p.Method=="cash"&&p.Status=="approved").Sum(p=>p.Amount);var deposits=x.Movements.Where(m=>m.Kind=="deposit").Sum(m=>m.Amount);var withdrawals=x.Movements.Where(m=>m.Kind=="withdrawal").Sum(m=>m.Amount);return new(x.Id,x.OpenedAt,x.ClosedAt,x.OpeningAmount,cash,deposits,withdrawals,x.OpeningAmount+cash+deposits-withdrawals,x.Status,x.CountedAmount);}
    private static decimal Round(decimal x)=>decimal.Round(x,2,MidpointRounding.AwayFromZero);
    private static string? CleanUpper(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim().ToUpperInvariant();
}
