using System.Data;
using Microsoft.EntityFrameworkCore;
using PuntoDeVentaAtlas.Web.Data;
using PuntoDeVentaAtlas.Web.Models;
namespace PuntoDeVentaAtlas.Web.Services;
public sealed class ManufacturingService(AtlasDbContext db,ICurrentUserContext current)
{
 public async Task<IReadOnlyList<RecipeSummary>> ListAsync(CancellationToken ct)=>await db.Recipes.AsNoTracking().Where(x=>x.StoreId==current.StoreId&&x.Active).OrderBy(x=>x.Product.Name).Select(x=>new RecipeSummary(x.Id,(int)x.ProductId,x.Product.Name,x.OutputQuantity,x.Components.Count)).ToListAsync(ct);
 public async Task<RecipeSummary> SaveRecipeAsync(SaveRecipeRequest x,CancellationToken ct)
 {
  if(x.OutputQuantity<=0||x.Components.Count==0)throw new InvalidOperationException("La receta requiere rendimiento y al menos una materia prima válidos.");if(x.Components.Any(c=>c.ProductId<=0||c.Quantity<=0))throw new InvalidOperationException("Los componentes deben tener producto y cantidad válidos.");if(x.Components.Any(c=>c.ProductId==x.ProductId))throw new InvalidOperationException("El producto terminado no puede consumirse a sí mismo.");
  var ids=x.Components.Select(c=>(long)c.ProductId).Append(x.ProductId).Distinct().ToList();var products=await db.Products.Where(p=>p.StoreId==current.StoreId&&ids.Contains(p.Id)&&p.Active).ToDictionaryAsync(p=>p.Id,ct);if(products.Count!=ids.Count)throw new InvalidOperationException("Hay productos inexistentes o de otra sucursal.");
  var existing=await db.Recipes.Include(r=>r.Components).FirstOrDefaultAsync(r=>r.StoreId==current.StoreId&&r.ProductId==x.ProductId&&r.Active,ct);if(existing is null){existing=new(){StoreId=current.StoreId,ProductId=x.ProductId};db.Recipes.Add(existing);}else db.RecipeLines.RemoveRange(existing.Components);existing.OutputQuantity=x.OutputQuantity;existing.Components=x.Components.Select(c=>new RecipeLineEntity{ProductId=c.ProductId,Quantity=c.Quantity}).ToList();db.AuditLog.Add(new(){StoreId=current.StoreId,UserId=current.UserId,Action="recipe.saved",Entity="recipe",EntityId=products[x.ProductId].Sku});await db.SaveChangesAsync(ct);return new(existing.Id,x.ProductId,products[x.ProductId].Name,x.OutputQuantity,x.Components.Count);
 }
 public async Task<ProductionResult> ProduceAsync(ProduceRequest x,CancellationToken ct)
 {
  if(x.Batches<=0)throw new InvalidOperationException("El número de lotes debe ser mayor que cero.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var recipe=await db.Recipes.Include(r=>r.Product).Include(r=>r.Components).FirstOrDefaultAsync(r=>r.Id==x.RecipeId&&r.StoreId==current.StoreId&&r.Active,ct)??throw new InvalidOperationException("Receta no encontrada.");var ids=recipe.Components.Select(c=>c.ProductId).Append(recipe.ProductId).Distinct().ToList();var products=await db.Products.Where(p=>p.StoreId==current.StoreId&&ids.Contains(p.Id)&&p.Active).ToDictionaryAsync(p=>p.Id,ct);if(products.Count!=ids.Count)throw new InvalidOperationException("La receta contiene productos inexistentes, inactivos o de otra sucursal.");var folio=$"F-{DateTime.Now:yyyyMMdd-HHmmssfff}";
  foreach(var line in recipe.Components){var p=products[line.ProductId];var needed=line.Quantity*x.Batches;if(p.Stock<needed)throw new InvalidOperationException($"Materia prima insuficiente: {p.Name}. Disponible {p.Stock}, requerida {needed}.");p.Stock-=needed;db.InventoryMovements.Add(new(){ProductId=p.Id,UserId=current.UserId,Kind="production.consume",Quantity=-needed,StockAfter=p.Stock,Note=folio,CreatedAt=DateTime.Now});}
  var output=products[recipe.ProductId];var produced=recipe.OutputQuantity*x.Batches;output.Stock+=produced;db.InventoryMovements.Add(new(){ProductId=output.Id,UserId=current.UserId,Kind="production.output",Quantity=produced,StockAfter=output.Stock,Note=folio,CreatedAt=DateTime.Now});db.ProductionOrders.Add(new(){StoreId=current.StoreId,RecipeId=recipe.Id,ProductId=output.Id,UserId=current.UserId,Folio=folio,Batches=x.Batches,QuantityProduced=produced});db.AuditLog.Add(new(){StoreId=current.StoreId,UserId=current.UserId,Action="production.completed",Entity="production",EntityId=folio,Detail=$"{output.Name}: {produced}"});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(folio,output.Name,produced,DateTime.Now);
 }
}
