CREATE DATABASE IF NOT EXISTS atlas_pos CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE atlas_pos;

CREATE TABLE IF NOT EXISTS stores (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(160) NOT NULL, rfc VARCHAR(13), timezone VARCHAR(64) NOT NULL DEFAULT 'America/Mexico_City', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6));
CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(160) NOT NULL, email VARCHAR(190) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(40) NOT NULL, active BIT NOT NULL DEFAULT 1, UNIQUE KEY uq_users_email(email), FOREIGN KEY(store_id) REFERENCES stores(id));
CREATE TABLE IF NOT EXISTS categories (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(120) NOT NULL, active BIT NOT NULL DEFAULT 1, FOREIGN KEY(store_id) REFERENCES stores(id));
CREATE TABLE IF NOT EXISTS products (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, category_id BIGINT, sku VARCHAR(60) NOT NULL, barcode VARCHAR(80), name VARCHAR(180) NOT NULL, unit VARCHAR(12) NOT NULL, is_weighted BIT NOT NULL DEFAULT 0, price DECIMAL(18,2) NOT NULL, cost DECIMAL(18,4) NOT NULL DEFAULT 0, tax_rate DECIMAL(7,4) NOT NULL DEFAULT 0, stock DECIMAL(18,3) NOT NULL DEFAULT 0, minimum_stock DECIMAL(18,3) NOT NULL DEFAULT 0, active BIT NOT NULL DEFAULT 1, UNIQUE KEY uq_product_sku(store_id,sku), UNIQUE KEY uq_product_barcode(store_id,barcode), INDEX ix_product_search(store_id,name), FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS customers (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(180) NOT NULL, rfc VARCHAR(13), legal_name VARCHAR(220), fiscal_regime VARCHAR(4), fiscal_zip VARCHAR(5), cfdi_use VARCHAR(4), email VARCHAR(190), phone VARCHAR(30), FOREIGN KEY(store_id) REFERENCES stores(id), INDEX ix_customer_rfc(store_id,rfc));
CREATE TABLE IF NOT EXISTS cash_shifts (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, user_id BIGINT NOT NULL, opened_at DATETIME(6) NOT NULL, closed_at DATETIME(6), opening_amount DECIMAL(18,2) NOT NULL, expected_amount DECIMAL(18,2), counted_amount DECIMAL(18,2), status VARCHAR(20) NOT NULL, FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS sales (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, shift_id BIGINT NOT NULL, customer_id BIGINT, folio VARCHAR(40) NOT NULL, subtotal DECIMAL(18,2) NOT NULL, discount DECIMAL(18,2) NOT NULL, tax DECIMAL(18,2) NOT NULL, total DECIMAL(18,2) NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE KEY uq_sale_folio(store_id,folio), FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(shift_id) REFERENCES cash_shifts(id), FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE IF NOT EXISTS sale_lines (id BIGINT PRIMARY KEY AUTO_INCREMENT, sale_id BIGINT NOT NULL, product_id BIGINT NOT NULL, description VARCHAR(180) NOT NULL, quantity DECIMAL(18,3) NOT NULL, unit_price DECIMAL(18,2) NOT NULL, tax DECIMAL(18,2) NOT NULL, total DECIMAL(18,2) NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS payments (id BIGINT PRIMARY KEY AUTO_INCREMENT, sale_id BIGINT NOT NULL, method VARCHAR(24) NOT NULL, amount DECIMAL(18,2) NOT NULL, reference VARCHAR(160), authorization VARCHAR(100), provider VARCHAR(80), status VARCHAR(24) NOT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(id));
CREATE TABLE IF NOT EXISTS invoices (id BIGINT PRIMARY KEY AUTO_INCREMENT, sale_id BIGINT NOT NULL, uuid CHAR(36), rfc VARCHAR(13) NOT NULL, status VARCHAR(24) NOT NULL, xml LONGBLOB, pdf LONGBLOB, stamped_at DATETIME(6), FOREIGN KEY(sale_id) REFERENCES sales(id));
CREATE TABLE IF NOT EXISTS inventory_movements (id BIGINT PRIMARY KEY AUTO_INCREMENT, product_id BIGINT NOT NULL, user_id BIGINT, sale_id BIGINT, kind VARCHAR(30) NOT NULL, quantity DECIMAL(18,3) NOT NULL, stock_after DECIMAL(18,3) NOT NULL, note VARCHAR(255), created_at DATETIME(6) NOT NULL, FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(sale_id) REFERENCES sales(id), INDEX ix_movements_product_date(product_id,created_at));
CREATE TABLE IF NOT EXISTS signatures (id BIGINT PRIMARY KEY AUTO_INCREMENT, sale_id BIGINT NOT NULL, device_id VARCHAR(120), image LONGBLOB NOT NULL, biometric_data LONGBLOB, captured_at DATETIME(6) NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(id));
CREATE TABLE IF NOT EXISTS suppliers (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(180) NOT NULL, rfc VARCHAR(13), email VARCHAR(190), phone VARCHAR(30), active BIT NOT NULL DEFAULT 1, FOREIGN KEY(store_id) REFERENCES stores(id));
CREATE TABLE IF NOT EXISTS purchases (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, supplier_id BIGINT NOT NULL, folio VARCHAR(50) NOT NULL, total DECIMAL(18,2) NOT NULL, status VARCHAR(24) NOT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(supplier_id) REFERENCES suppliers(id));
CREATE TABLE IF NOT EXISTS purchase_lines (id BIGINT PRIMARY KEY AUTO_INCREMENT, purchase_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity DECIMAL(18,3) NOT NULL, unit_cost DECIMAL(18,4) NOT NULL, total DECIMAL(18,2) NOT NULL, FOREIGN KEY(purchase_id) REFERENCES purchases(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS sale_returns (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, sale_id BIGINT NOT NULL, folio VARCHAR(50) NOT NULL, total DECIMAL(18,2) NOT NULL, reason VARCHAR(255) NOT NULL, status VARCHAR(24) NOT NULL, created_at DATETIME(6) NOT NULL, FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(sale_id) REFERENCES sales(id));
CREATE TABLE IF NOT EXISTS audit_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, user_id BIGINT, action VARCHAR(50) NOT NULL, entity VARCHAR(50) NOT NULL, entity_id VARCHAR(80), detail JSON, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(user_id) REFERENCES users(id), INDEX ix_audit_date(store_id,created_at));
CREATE TABLE IF NOT EXISTS app_settings (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, setting_key VARCHAR(100) NOT NULL, setting_value JSON NOT NULL, UNIQUE KEY uq_setting(store_id,setting_key), FOREIGN KEY(store_id) REFERENCES stores(id));

INSERT INTO stores(id,name,rfc) VALUES(1,'Sucursal Centro',NULL) ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users(id,store_id,name,email,password_hash,role) VALUES(1,1,'Administrador','admin@atlas.local','CONFIGURAR_IDENTITY','Administrator') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories(id,store_id,name) VALUES (1,1,'Abarrotes'),(2,1,'Lácteos'),(3,1,'Frutas y verduras'),(4,1,'Panadería'),(5,1,'Bebidas'),(6,1,'Limpieza') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO products(id,store_id,category_id,sku,barcode,name,unit,is_weighted,price,cost,tax_rate,stock,minimum_stock) VALUES
(1,1,1,'CAF-001','7501001000011','Café artesanal 500 g','pza',0,149,90,.16,24,5),(2,1,2,'LEC-001','7501001000028','Leche entera 1 L','pza',0,29.50,21,0,48,10),(3,1,3,'MAN-KG','2000000001012','Manzana Gala','kg',1,46.90,28,0,18.75,5),(4,1,4,'PAN-001','7501001000042','Pan integral','pza',0,54,32,0,12,4),(5,1,5,'REF-600','7501001000059','Refresco 600 ml','pza',0,22,14,.16,6,8),(6,1,6,'JAB-001','7501001000066','Jabón líquido 500 ml','pza',0,67.50,41,.16,31,6),(7,1,2,'QUE-KG','2000000001074','Queso manchego','kg',1,189,130,0,8.4,3),(8,1,1,'GAL-001','7501001000080','Galletas de avena','pza',0,38,22,.16,19,5)
ON DUPLICATE KEY UPDATE name=VALUES(name),price=VALUES(price);
INSERT INTO customers(id,store_id,name,rfc,email,phone) VALUES(1,1,'Público general','XAXX010101000',NULL,NULL),(2,1,'Mariana López','LOPM850312AB2','mariana@correo.mx','55 1234 5678'),(3,1,'Comercial del Centro SA de CV','CCE201015KQ4','compras@comercial.mx','55 8765 4321') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO cash_shifts(id,store_id,user_id,opened_at,opening_amount,status) VALUES(1,1,1,CURRENT_TIMESTAMP(6),0,'open') ON DUPLICATE KEY UPDATE status=IF(status='closed','closed',VALUES(status));
INSERT INTO suppliers(id,store_id,name,rfc,email,phone) VALUES(1,1,'Proveedor General',NULL,'ventas@proveedor.local',NULL) ON DUPLICATE KEY UPDATE name=VALUES(name);
